(()=>{'use strict';const get=id=>document.getElementById(id),form=get('adForm'),status=get('adEditorStatus');const placementNames={portada:'Portada principal',general:'Entre secciones',paraguay:'Paraguay',uruguay:'Uruguay'},zone='America/Argentina/Buenos_Aires',mime={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};let editing=null,publicRows=[],publicRequest=0,manageRequest=0;
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function https(value,optional=false){if(!value&&optional)return '';try{const u=new URL(value);if(u.protocol==='https:')return u.href;}catch{}throw Error('Los enlaces deben comenzar con https://.');}
function localStamp(value){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)),p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function instant(value){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('Completá inicio y fin.');const target=Date.parse(value+'Z');if(!Number.isFinite(target))throw Error('Fecha inválida.');let result=target;for(let i=0;i<4;i++){const delta=target-Date.parse(localStamp(result)+'Z');if(!delta)break;result+=delta;}if(localStamp(result)!==value)throw Error('Fecha u hora inválida.');return new Date(result).toISOString();}
function eligible(r,now=Date.now()){return r.activa&&new Date(r.empieza_at).getTime()<=now&&new Date(r.termina_at).getTime()>now;}
function renderAds(){for(const slot of document.querySelectorAll('[data-ad-slot]')){slot.replaceChildren();const position=slot.dataset.adSlot,r=publicRows.find(x=>x.ubicacion===position&&eligible(x));slot.append(node('span','PUBLICIDAD','ad-label'));if(r){const link=node('a','','ad-campaign');try{link.href=https(r.enlace);}catch{continue;}link.target='_blank';link.rel='sponsored noopener noreferrer';if(r.imagen){try{const img=document.createElement('img');img.src=https(r.imagen);img.alt='Publicidad de '+r.anunciante;img.loading=position==='portada'?'eager':'lazy';img.decoding='async';img.onerror=()=>img.remove();link.append(img);}catch{}}const text=node('div','','ad-campaign-text');text.append(node('strong',r.anunciante));if(r.texto)text.append(node('p',r.texto));text.append(node('span','Conocé más ↗','ad-cta'));link.append(text);slot.append(link);}else{const link=node('a','','ad-house');link.href='https://wa.me/5492634277869?text='+encodeURIComponent('Hola, quiero consultar por publicidad en ZETA24. Espacio: '+placementNames[position]);link.target='_blank';link.rel='noopener noreferrer';const text=node('div','');text.append(node('span','LLEGÁ A NUESTRA COMUNIDAD','ad-house-kicker'),node('strong','Tu negocio en ZETA24'),node('p','Consultá por este espacio publicitario.'));link.append(text,node('span','HABLEMOS POR WHATSAPP ↗','ad-house-button'));slot.append(link);}}}
async function loadPublic(){const id=++publicRequest;try{const now=new Date().toISOString(),{data,error}=await sb.from('zeta_anuncios').select('*').eq('activa',true).lte('empieza_at',now).gt('termina_at',now).order('created_at',{ascending:false}).limit(200);if(error)throw error;if(id!==publicRequest)return;publicRows=data||[];renderAds();}catch{if(id===publicRequest)renderAds();}}
function reset(){editing=null;form.reset();get('adSave').textContent='GUARDAR ANUNCIO';status.textContent='';}
function field(name,value){form.elements.namedItem(name).value=value;}
async function loadManage(){const request=++manageRequest;get('adManage').replaceChildren();status.textContent='Consultando anuncios…';try{const {data:{session}}=await sb.auth.getSession();if(!session)throw Error('Iniciá sesión en Redacción.');const {data,error}=await sb.from('zeta_anuncios').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;if(request!==manageRequest)return;status.textContent=data.length?'Anuncios cargados. Si coinciden varios en una ubicación, aparece el creado más recientemente.':'Todavía no hay anuncios cargados.';for(const r of data){const box=node('article','','ad-manage-row'),state=!r.activa?'Pausado':new Date(r.termina_at)<=new Date()?'Finalizado':new Date(r.empieza_at)>new Date()?'Programado':'Vigente';box.append(node('strong',r.anunciante),node('p',placementNames[r.ubicacion]+' · '+state),node('small',localStamp(r.empieza_at).replace('T',' ')+' → '+localStamp(r.termina_at).replace('T',' ')+' · Hora de Argentina'));const actions=node('div','','ad-manage-actions'),edit=node('button','EDITAR');edit.type='button';edit.onclick=()=>{reset();editing=r.id;field('adSponsor',r.anunciante);field('adText',r.texto);field('adPlacement',r.ubicacion);field('adLink',r.enlace);field('adImage',r.imagen);field('adStart',localStamp(r.empieza_at));field('adEnd',localStamp(r.termina_at));form.elements.namedItem('adActive').checked=r.activa;get('adSave').textContent='GUARDAR CAMBIOS';status.textContent='Editando anuncio de '+r.anunciante;form.scrollIntoView({behavior:'smooth',block:'start'});};const pause=node('button',r.activa?'PAUSAR':'HABILITAR');pause.type='button';pause.onclick=async()=>{pause.disabled=true;try{const {error}=await sb.rpc('zeta_pausar_anuncio',{p_id:r.id,p_activa:!r.activa});if(error)throw error;await loadPublic();await loadManage();}catch(e){status.textContent='No se pudo cambiar el estado: '+e.message;}finally{pause.disabled=false;}};actions.append(edit,pause);box.append(actions);get('adManage').append(box);}}catch(e){if(request===manageRequest)status.textContent='No se pudieron cargar: '+e.message;}}
form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);let start,end,link,image;const photo=fd.get('adPhoto');try{start=instant(fd.get('adStart'));end=instant(fd.get('adEnd'));if(end<=start)throw Error('El fin debe ser posterior al inicio.');link=https(fd.get('adLink').trim());image=https(fd.get('adImage').trim(),true);if(photo?.size&&(!mime[photo.type]||photo.size>5242880))throw Error('La imagen debe ser JPG, PNG o WebP de hasta 5 MB.');}catch(e){status.textContent=e.message;return;}get('adSave').disabled=true;status.textContent='Guardando anuncio…';try{if(photo?.size){const path=crypto.randomUUID()+'.'+mime[photo.type],bucket=sb.storage.from('zeta-publicidad'),{error}=await bucket.upload(path,photo,{contentType:photo.type,upsert:false});if(error)throw error;image=bucket.getPublicUrl(path).data.publicUrl;field('adImage',image);form.elements.namedItem('adPhoto').value='';}const {error}=await sb.rpc('zeta_guardar_anuncio',{p_id:editing,p_anunciante:fd.get('adSponsor').trim(),p_texto:fd.get('adText').trim(),p_enlace:link,p_imagen:image,p_ubicacion:fd.get('adPlacement'),p_empieza:start,p_termina:end,p_activa:!!fd.get('adActive')});if(error)throw error;reset();await loadPublic();await loadManage();status.textContent='Anuncio guardado. Se mostrará mientras esté habilitado y dentro de sus fechas.';}catch(e){status.textContent='No se pudo guardar: '+e.message;}finally{get('adSave').disabled=false;}};
get('adNew').onclick=reset;get('adLoad').onclick=loadManage;sb.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){manageRequest++;get('adManage').replaceChildren();reset();}if(event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(loadPublic,0);});renderAds();loadPublic();setInterval(()=>{if(!document.hidden)loadPublic();},60000);
})();
