(()=>{'use strict';const by=id=>document.getElementById(id),form=by('agendaForm'),status=by('agendaStatus'),editorStatus=by('agendaEditorStatus');const zones={Argentina:'America/Argentina/Buenos_Aires',Paraguay:'America/Asuncion',Uruguay:'America/Montevideo'};let rows=[],editing=null,request=0;
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function localStamp(value,zone){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function instant(value,zone){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('Completá las fechas y horas.');const target=Date.parse(value+'Z');if(!Number.isFinite(target))throw Error('Fecha inválida.');let result=target;for(let i=0;i<4;i++){const local=Date.parse(localStamp(result,zone)+'Z'),delta=target-local;if(delta===0)break;result+=delta;}if(localStamp(result,zone)!==value)throw Error('Esa hora no existe en el país seleccionado. Elegí otra hora.');return new Date(result).toISOString();}
function dateLabel(value,zone){return new Date(value).toLocaleString('es-AR',{timeZone:zone,weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function setField(name,value){form.elements.namedItem(name).value=value;}
function render(){const country=by('agendaCountry').value,category=by('agendaCategory').value,visible=rows.filter(r=>(!country||r.pais===country)&&(!category||r.categoria===category)&&new Date(r.termina_at)>new Date());const cards=by('agendaCards');cards.replaceChildren();if(!visible.length)cards.append(node('p','Todavía no hay próximas actividades publicadas con estos filtros.'));for(const r of visible){const card=node('article','','agenda-card'),tag=node('span',r.pais+' · '+r.categoria,'cat');card.append(tag,node('h3',r.titulo),node('p',dateLabel(r.empieza_at,r.zona)+' · Hora local','agenda-date'),node('p','Hasta '+dateLabel(r.termina_at,r.zona),'agenda-end'),node('strong',r.ciudad+' · '+r.lugar));if(r.descripcion)card.append(node('p',r.descripcion,'agenda-description'));if(r.enlace){try{const url=new URL(r.enlace);if(url.protocol==='https:'){const a=node('a','Información del organizador ↗');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}}catch{}}cards.append(card);}const list=by('agendaManage');list.replaceChildren();for(const r of rows){const line=node('div','','agenda-manage-row');line.append(node('span',r.titulo+' · '+r.pais+' · '+dateLabel(r.empieza_at,r.zona)));const edit=node('button','EDITAR');edit.type='button';edit.onclick=()=>{editing=r.id;setField('eventId',r.id);setField('eventTitle',r.titulo);setField('eventCountry',r.pais);setField('eventCategory',r.categoria);setField('eventCity',r.ciudad);setField('eventPlace',r.lugar);setField('eventStart',localStamp(r.empieza_at,r.zona));setField('eventEnd',localStamp(r.termina_at,r.zona));setField('eventDescription',r.descripcion);setField('eventLink',r.enlace);by('agendaSave').textContent='GUARDAR CAMBIOS';editorStatus.textContent='Editando: '+r.titulo;form.scrollIntoView({behavior:'smooth',block:'start'});};const remove=node('button','RETIRAR');remove.type='button';remove.onclick=async()=>{remove.disabled=true;editorStatus.textContent='Retirando evento…';try{const {error}=await sb.rpc('zeta_retirar_evento',{p_id:r.id});if(error)throw error;if(editing===r.id)reset();await load();editorStatus.textContent='Evento retirado de la agenda pública.';}catch(e){editorStatus.textContent='No se pudo retirar: '+e.message;}finally{remove.disabled=false;}};line.append(edit,remove);list.append(line);}if(!rows.length)list.append(node('p','No hay próximos eventos publicados.'));}
function reset(){editing=null;form.reset();setField('eventId','');by('agendaSave').textContent='PUBLICAR EVENTO';editorStatus.textContent='';}
async function load(){const id=++request;status.textContent='Consultando agenda…';try{const {data,error}=await sb.from('zeta_eventos').select('*').eq('activa',true).gte('termina_at',new Date().toISOString()).order('empieza_at',{ascending:true}).limit(200);if(error)throw error;if(id!==request)return;rows=data||[];render();status.textContent=rows.length?'Próximas actividades · Actualizado a las '+new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})+'.':'La agenda está lista para recibir las primeras actividades.';}catch{if(id!==request)return;status.textContent='No se pudo actualizar la agenda. Pulsá ACTUALIZAR para volver a intentar.';if(!rows.length)by('agendaCards').replaceChildren(node('p','Las actividades no están disponibles por el momento.'));}}
form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),country=fd.get('eventCountry'),zone=zones[country];let start,end,link=fd.get('eventLink').trim();try{start=instant(fd.get('eventStart'),zone);end=instant(fd.get('eventEnd'),zone);if(end<=start)throw Error('La finalización debe ser posterior al inicio.');if(new Date(end)<=new Date())throw Error('El evento ya terminó. Revisá la fecha.');if(link&&new URL(link).protocol!=='https:')throw Error('El enlace debe comenzar con https://.');}catch(error){editorStatus.textContent=error.message;return;}const button=by('agendaSave');button.disabled=true;editorStatus.textContent='Guardando evento…';try{const {error}=await sb.rpc('zeta_guardar_evento',{p_id:editing,p_titulo:fd.get('eventTitle').trim(),p_pais:country,p_ciudad:fd.get('eventCity').trim(),p_lugar:fd.get('eventPlace').trim(),p_categoria:fd.get('eventCategory'),p_empieza:start,p_termina:end,p_zona:zone,p_descripcion:fd.get('eventDescription').trim(),p_enlace:link});if(error)throw error;reset();await load();editorStatus.textContent='Evento guardado en la agenda online.';}catch(error){editorStatus.textContent='No se pudo guardar: '+error.message;}finally{button.disabled=false;}};
by('agendaNew').onclick=reset;by('agendaRefresh').onclick=load;by('agendaCountry').onchange=render;by('agendaCategory').onchange=render;load();setInterval(()=>{if(!document.hidden)load();},5*60000);
})();
