const SUPABASE_URL='https://lzgxiacmudzntxdfrvkc.supabase.co';
const SUPABASE_KEY='sb_publishable_SgTDV6_RvDZPwZomhpy5aA_JkZWlJsL';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let externalNews=[]; let cache=[]; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function fmt(x){return new Date(x).toLocaleString('es-AR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
function card(p){const image=safeURL(p.imagen_url||'');return `<article class="card clickable ${image?'has-photo':''}" data-id="${esc(p.id)}">${image?`<figure class="card-media"><img src="${esc(image)}" alt="${esc(p.titulo)}" loading="lazy" decoding="async">${p.imagen_credito?`<figcaption>${esc(p.imagen_credito)}</figcaption>`:''}</figure>`:''}<span class="cat">${esc(p.seccion)}${p.demo?' · DEMOSTRACIÓN':''}</span><h3>${esc(p.titulo)}</h3><p>${esc(p.copete||'')}</p><small>${fmt(p.created_at)} · ${esc(p.autor||'Redacción ZETA 24')}</small></article>`}
async function load(){const {data,error}=await sb.from('noticias').select('*').eq('publicada',true).order('created_at',{ascending:false}); if(error){console.error(error);cache=[];toast('No se pudieron cargar las noticias de redacción')}else cache=data||[]; render(); await loadExternal(); await loadUrgent()}
function featuredPost(){return cache.find(x=>x.destacada)||cache[0]}
function secondaryNews(){const featured=featuredPost();return cache.filter(p=>!featured||String(p.id)!==String(featured.id))}
function render(){const assigned=new Set(['ZONA ESTE','MENDOZA','ARGENTINA','INTERNACIONALES','ECONOMÍA','DEPORTES','ESPECTÁCULOS','TECNOLOGÍA Y CIENCIA','AMBIENTE','PARAGUAY','URUGUAY','CLIMA','CLIMA PARAGUAY','CLIMA URUGUAY']);const remaining=secondaryNews().filter(p=>!assigned.has(p.seccion));$('#newsGrid').innerHTML=remaining.map(card).join('');$('#newsGrid').closest('section').hidden=!remaining.length;$('#latestList').innerHTML='';$('#latestList').closest('section').hidden=true;if(cache[0])$('#ticker').textContent=cache[0].titulo;renderSections();filterNews()}

function openArticle(id){const p=cache.find(x=>String(x.id)===String(id));if(!p)return;$('#articleCat').textContent=p.seccion;$('#articleTitle').textContent=p.titulo;$('#articleMeta').textContent=`${fmt(p.created_at)} · ${p.autor||'Redacción ZETA 24'}`;const image=safeURL(p.imagen_url||'');$('#articleBody').innerHTML=(image?`<figure class="article-photo"><img src="${esc(image)}" alt="${esc(p.titulo)}">${p.imagen_credito?`<figcaption>${esc(p.imagen_credito)}</figcaption>`:''}</figure>`:'')+String(p.contenido).split(/\n+/).map(x=>`<p>${esc(x)}</p>`).join('');$('#articleModal').classList.add('open');history.replaceState(null,'','#nota='+id)}
$('#closeArticle').onclick=()=>{$('#articleModal').classList.remove('open');history.replaceState(null,'',location.pathname)};
$('#shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:$('#articleTitle').textContent,url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Enlace copiado')}}catch{}};
$('#search').addEventListener('input',filterNews);
async function authUI(){const {data:{session}}=await sb.auth.getSession();$('#authBox').style.display=session?'none':'block';$('#editorOnline').style.display=session?'block':'none';if(session)$('#userEmail').textContent=session.user.email}
$('#editorBtn').onclick=async()=>{$('#editorModal').classList.add('open');await authUI()};$('#closeEditor').onclick=()=>$('#editorModal').classList.remove('open');
$('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return toast('No se pudo iniciar sesión: '+error.message);e.target.reset();await authUI();toast('Redacción conectada')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();await authUI();toast('Sesión cerrada')};
$('#postForm').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button[type="submit"]'),fd=new FormData(form);let image=fd.get('newsImage').trim(),photo=fd.get('newsPhoto');if(image&&!safeURL(image))return toast('La imagen debe tener un enlace HTTPS válido');if(photo?.size&&(!['image/jpeg','image/png','image/webp'].includes(photo.type)||photo.size>5242880))return toast('Elegí una foto JPG, PNG o WebP de hasta 5 MB');button.disabled=true;try{if(photo?.size){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[photo.type],path=crypto.randomUUID()+'.'+ext,bucket=sb.storage.from('zeta-noticias');const {error}=await bucket.upload(path,photo,{contentType:photo.type,upsert:false});if(error)throw error;image=bucket.getPublicUrl(path).data.publicUrl;form.elements.namedItem('newsImage').value=image;form.elements.namedItem('newsPhoto').value='';}const row={titulo:fd.get('title').trim(),copete:fd.get('summary').trim(),seccion:fd.get('section'),autor:fd.get('author').trim()||'Redacción ZETA 24',contenido:fd.get('body').trim(),publicada:true,destacada:false,imagen_url:image||null,imagen_credito:fd.get('newsCredit').trim()||null};const {error}=await sb.from('noticias').insert(row);if(error)throw error;form.reset();$('#editorModal').classList.remove('open');await load();toast('¡Noticia publicada online!');}catch(error){toast('No se pudo publicar: '+error.message);}finally{button.disabled=false;}};
async function loadUrgent(){const {data}=await sb.from('ultimo_momento').select('*').eq('activo',true).order('created_at',{ascending:false}).limit(1);if(data?.[0])$('#ticker').textContent=data[0].texto}
$('#urgentBtn').onclick=async()=>{const v=$('#urgentInput').value.trim();if(!v)return toast('Escribí primero el titular urgente');const {data:{session}}=await sb.auth.getSession();if(!session){$('#editorModal').classList.add('open');await authUI();return toast('Iniciá sesión en Redacción para actualizar Último Momento')}const {error}=await sb.from('ultimo_momento').insert({texto:v,activo:true});if(error)return toast('No se pudo actualizar: '+error.message);$('#ticker').textContent=v;$('#urgentInput').value='';toast('Último Momento publicado online')};
function showRadio(){const el=$('#radio');el.scrollIntoView({behavior:'smooth',block:'center'});history.replaceState(null,'','#radio')}$('#radioBtn').onclick=showRadio;$('#radioMini').onclick=showRadio;
const d=new Date();$('#fecha').textContent=d.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});load().then(()=>{if(location.hash.startsWith('#nota='))openArticle(location.hash.slice(6))});

const sections=[['MENDOZA','mendoza','Mendoza'],['ARGENTINA','argentina','Argentina'],['INTERNACIONALES','internacionales','Internacionales'],['ECONOMÍA','economia','Economía'],['DEPORTES','deportes','Deportes'],['ESPECTÁCULOS','espectaculos','Espectáculos'],['TECNOLOGÍA Y CIENCIA','tecnologia','Tecnología y ciencia'],['AMBIENTE','ambiente','Ambiente']];
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:''}catch{return ''}}
function externalCard(p){const url=safeURL(p.url);if(!url)return '';const image=safeURL(p.imagen_url||'');return `<article class="card external-card ${image?'has-photo':''}">${image?`<figure class="card-media"><a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(image)}" alt="${esc(p.titulo)}" loading="lazy" decoding="async"></a><figcaption>${esc(p.fuente)}${p.imagen_credito?' · '+esc(p.imagen_credito):''}</figcaption></figure>`:''}<span class="cat">${esc(p.fuente)} · FUENTE EXTERNA</span><h3><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(p.titulo)}</a></h3><small>${fmt(p.published_at)}</small><a class="read-source" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Leer en ${esc(p.fuente)} ↗</a></article>`}
function varied(rows){const groups=new Map();for(const p of rows){if(!groups.has(p.fuente))groups.set(p.fuente,[]);groups.get(p.fuente).push(p)}const out=[],titles=new Set();while([...groups.values()].some(g=>g.length)&&out.length<12){for(const g of groups.values()){const p=g.shift();if(!p)continue;const key=p.titulo.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');if(!titles.has(key)){out.push(p);titles.add(key)}}}return out.slice(0,12)}
function renderSections(){renderFeatured();renderWeatherReports();renderRegional();const local=secondaryNews().filter(p=>p.seccion==='ZONA ESTE'&&!p.demo);$('#localNews').innerHTML=local.map(card).join('');$('#localNews').parentElement.hidden=!local.length;const sectionHTML=sections.map(([key,id,label])=>{const own=secondaryNews().filter(p=>p.seccion===key&&!p.demo);const ext=varied(externalNews.filter(p=>p.seccion===key));if(!own.length&&!ext.length)return '';return `<section class="latest news-section section-${id}" id="${id}"><div class="section-title"><h2>${label}</h2><span>Medios y redacción</span></div><div class="published">${own.map(card).join('')}${ext.map(externalCard).join('')}${own.length||ext.length?'':'<p class="empty">Todavía no hay noticias disponibles en esta sección.</p>'}</div></section>`}).join('');const holder=document.createElement('div');holder.innerHTML=sectionHTML;$('#prioritySections').replaceChildren();$('#externalSections').replaceChildren();for(const node of [...holder.children]){(['mendoza','argentina'].includes(node.id)?$('#prioritySections'):$('#externalSections')).append(node);}$$('[data-id]').forEach(el=>el.onclick=()=>openArticle(el.dataset.id));filterNews()}
function filterNews(){bindNewsImages();const q=$('#search').value.trim().toLowerCase();$$('main .card').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q));composeEdition()}
async function loadExternal(){try{const [news,status]=await Promise.all([sb.from('noticias_externas').select('*').gte('published_at',new Date(Date.now()-7*86400000).toISOString()).order('published_at',{ascending:false}).limit(800),sb.from('fuentes_rss').select('nombre,ultima_ok,ultimo_error').eq('activa',true)]);if(news.error||status.error)throw news.error||status.error;externalNews=news.data||[];const times=(status.data||[]).map(x=>x.ultima_ok).filter(Boolean).sort();const latest=times.at(-1);const failed=(status.data||[]).filter(x=>x.ultimo_error).length;$('#autoStatus').textContent=latest?`Última lectura de fuentes: ${fmt(latest)}. ${failed?failed+' fuentes no respondieron; se conservan sus titulares anteriores.':'Actualización programada cada 15 minutos.'}`:'Noticias automáticas pendientes de la primera actualización.';$('#autoBadge').textContent=latest?(Date.now()-new Date(latest)>45*60000?'DEMORADA':'ACTUALIZADAS'):'PENDIENTE';if(latest&&Date.now()-new Date(latest)>45*60000)$('#autoStatus').textContent+=' La actualización está demorada.'}catch{ $('#autoStatus').textContent='Noticias automáticas pendientes de activación o temporalmente sin conexión.';$('#autoBadge').textContent='PENDIENTE'}renderSections()}
setInterval(()=>{if(!document.hidden)loadExternal();},60*1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadExternal();});

function renderFeatured(){const p=featuredPost();const el=$('#featuredNews');el.hidden=!p;if(!p){el.innerHTML='';return}const photo=safeURL(p.imagen_url||'');el.innerHTML=`<article class="featured-article clickable" data-id="${esc(p.id)}">${photo?`<img src="${esc(photo)}" alt="" loading="lazy">`:''}<div><span class="cat">${esc(p.seccion)} · REDACCIÓN ZETA24</span>${photo&&p.imagen_credito?`<small class="featured-credit">Foto: ${esc(p.imagen_credito)}</small>`:''}<h2>${esc(p.titulo)}</h2><p>${esc(p.copete||'')}</p><small>${fmt(p.created_at)} · ${esc(p.autor||'Redacción ZETA24')}</small></div></article>`}

function renderWeatherReports(){const rows=secondaryNews().filter(p=>['CLIMA','CLIMA PARAGUAY','CLIMA URUGUAY'].includes(p.seccion)&&!p.demo).slice(0,6);$('#weatherReports').innerHTML=rows.length?rows.map(card).join(''):'<p>Todavía no hay informes publicados. Volvé pronto para leer el análisis de Estación Zúñiga.</p>';}

function renderRegional(){for(const [key,id] of [['PARAGUAY','paraguay'],['URUGUAY','uruguay']]){const own=secondaryNews().filter(p=>p.seccion===key&&!p.demo);const ext=varied(externalNews.filter(p=>p.seccion===key));$('#'+id+'News').innerHTML=own.map(card).join('')+ext.map(externalCard).join('');$('#'+id+'NewsStatus').textContent=ext.length?'Titulares de medios del país · Consultá la fecha y la fuente de cada nota.':own.length?'Noticias de nuestra redacción.':'Los titulares automáticos todavía no están disponibles. Podés consultar el medio de origen desde el enlace inferior.';const reports=secondaryNews().filter(p=>p.seccion==='CLIMA '+key&&!p.demo).slice(0,6);$('#'+id+'Reports').innerHTML=reports.length?reports.map(card).join(''):'<p>Pronto publicaremos informes y pronósticos de Estación Zúñiga para este país.</p>';}}

function bindNewsImages(){$$('main .card-media img').forEach(img=>{img.onerror=()=>{const figure=img.closest('figure');img.closest('.card')?.classList.remove('has-photo');figure?.remove();composeEdition();};});}

// Give each news section a single illustrated lead, without duplicating stories.
function composeEdition(){
 document.querySelectorAll('.news-section .published,#paraguayNews,#uruguayNews,#localNews').forEach(container=>{
  const cards=[...container.children].filter(el=>el.classList.contains('card'));
  for(const card of cards){
   card.classList.remove('edition-lead');
   if(!card.querySelector(':scope > .story-copy')){
    const copy=document.createElement('div');copy.className='story-copy';
    for(const node of [...card.childNodes])if(!(node.nodeType===1&&node.classList.contains('card-media')))copy.append(node);
    card.append(copy);
   }
  }
  const lead=cards.find(card=>!card.hidden&&card.classList.contains('has-photo'));
  if(lead){lead.classList.add('edition-lead');container.prepend(lead);}
 });
}
