const SUPABASE_URL='https://lzgxiacmudzntxdfrvkc.supabase.co';
const SUPABASE_KEY='sb_publishable_SgTDV6_RvDZPwZomhpy5aA_JkZWlJsL';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const DEMO=[{id:'bienvenida-zeta24',titulo:'ZETA 24: información local, clima y radio en un mismo lugar',copete:'Primera portada del nuevo medio digital con foco en la Zona Este, Mendoza, servicios y contenidos propios.',seccion:'INSTITUCIONAL',autor:'Redacción ZETA 24',created_at:'2026-10-07T16:30:00-03:00',contenido:'ZETA 24 comienza su etapa de desarrollo como portal digital. El proyecto integrará noticias, clima, servicios y Radio Zeta en una misma plataforma.\n\nEsta publicación es demostrativa y será reemplazada por contenido periodístico real al momento del lanzamiento.',demo:true}];
let cache=[]; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function fmt(x){return new Date(x).toLocaleString('es-AR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
function card(p){return `<article class="card clickable" data-id="${p.id}"><span class="cat">${esc(p.seccion)}</span><h3>${esc(p.titulo)}</h3><p>${esc(p.copete||'')}</p><small>${fmt(p.created_at)} · ${esc(p.autor||'Redacción ZETA 24')}</small></article>`}
async function load(){const {data,error}=await sb.from('noticias').select('*').eq('publicada',true).order('created_at',{ascending:false}); if(error){console.error(error);cache=DEMO;toast('Sin conexión a noticias: mostrando demo')}else cache=data.length?data:DEMO; render(); await loadUrgent()}
function render(){const feed=cache;$('#newsGrid').innerHTML=feed.slice(0,6).map(card).join('');$('#latestList').innerHTML=feed.slice(0,5).map(p=>`<div class="newsrow clickable" data-id="${p.id}"><span>${new Date(p.created_at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</span><b>${esc(p.titulo)}</b><em>${esc(p.seccion)}</em></div>`).join('');if(feed[0])$('#ticker').textContent=feed[0].titulo;$$('[data-id]').forEach(el=>el.onclick=()=>openArticle(el.dataset.id))}
function openArticle(id){const p=cache.find(x=>String(x.id)===String(id));if(!p)return;$('#articleCat').textContent=p.seccion;$('#articleTitle').textContent=p.titulo;$('#articleMeta').textContent=`${fmt(p.created_at)} · ${p.autor||'Redacción ZETA 24'}`;$('#articleBody').innerHTML=String(p.contenido).split(/\n+/).map(x=>`<p>${esc(x)}</p>`).join('');$('#articleModal').classList.add('open');history.replaceState(null,'','#nota='+id)}
$('#closeArticle').onclick=()=>{$('#articleModal').classList.remove('open');history.replaceState(null,'',location.pathname)};
$('#shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:$('#articleTitle').textContent,url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Enlace copiado')}}catch{}};
$('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('#newsGrid .card').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)?'':'none')});
async function authUI(){const {data:{session}}=await sb.auth.getSession();$('#authBox').style.display=session?'none':'block';$('#editorOnline').style.display=session?'block':'none';if(session)$('#userEmail').textContent=session.user.email}
$('#editorBtn').onclick=async()=>{$('#editorModal').classList.add('open');await authUI()};$('#closeEditor').onclick=()=>$('#editorModal').classList.remove('open');
$('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return toast('No se pudo iniciar sesión: '+error.message);e.target.reset();await authUI();toast('Redacción conectada')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();await authUI();toast('Sesión cerrada')};
$('#postForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const row={titulo:fd.get('title').trim(),copete:fd.get('summary').trim(),seccion:fd.get('section'),autor:fd.get('author').trim()||'Redacción ZETA 24',contenido:fd.get('body').trim(),publicada:true,destacada:false};const {error}=await sb.from('noticias').insert(row);if(error)return toast('No se pudo publicar: '+error.message);e.target.reset();$('#editorModal').classList.remove('open');await load();toast('¡Noticia publicada online!')};
async function loadUrgent(){const {data}=await sb.from('ultimo_momento').select('*').eq('activo',true).order('created_at',{ascending:false}).limit(1);if(data?.[0])$('#ticker').textContent=data[0].texto}
$('#urgentBtn').onclick=async()=>{const v=$('#urgentInput').value.trim();if(!v)return toast('Escribí primero el titular urgente');const {data:{session}}=await sb.auth.getSession();if(!session){$('#editorModal').classList.add('open');await authUI();return toast('Iniciá sesión en Redacción para actualizar Último Momento')}const {error}=await sb.from('ultimo_momento').insert({texto:v,activo:true});if(error)return toast('No se pudo actualizar: '+error.message);$('#ticker').textContent=v;$('#urgentInput').value='';toast('Último Momento publicado online')};
function avisoRadio(){toast('Radio Zeta: falta conectar el streaming real')}$('#radioBtn').onclick=avisoRadio;$('#playBtn').onclick=avisoRadio;$('#radioMini').onclick=avisoRadio;
const d=new Date();$('#fecha').textContent=d.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});load().then(()=>{if(location.hash.startsWith('#nota='))openArticle(location.hash.slice(6))});
