(()=>{'use strict';const el=id=>document.getElementById(id),content=el('pollContent'),status=el('pollStatus');let poll=null,busy=false,showResults=false,refreshId=0;
function item(tag,text,cls){const x=document.createElement(tag);x.textContent=text;if(cls)x.className=cls;return x;}
function savedVote(id){try{return localStorage.getItem('zeta24_vote_'+id)}catch{return null;}}
function device(){let id=localStorage.getItem('zeta24_poll_device');if(!id){id=crypto.randomUUID();localStorage.setItem('zeta24_poll_device',id);}return id;}
function draw(){content.replaceChildren();if(!poll){content.append(item('p','Pronto publicaremos una pregunta para nuestros lectores.'));return;}content.append(item('h3',poll.pregunta),item('p',(poll.abierta?'Cierra':'Cerró')+' el '+new Date(poll.cierra_at).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}),'poll-deadline'));const voted=savedVote(poll.id),results=showResults||voted!==null||!poll.abierta;
if(results){poll.opciones.forEach((option,i)=>{const count=Number(poll.votos[i]||0),pct=poll.total?Math.round(count/poll.total*100):0,row=item('div','','poll-result'),caption=item('div','','poll-caption');caption.append(item('span',option+(String(i)===voted?' · Tu voto':'')),item('strong',pct+'%'));const track=item('div','','poll-track'),bar=item('div','','poll-bar');bar.style.width=pct+'%';track.append(bar);row.append(caption,track,item('small',count+(count===1?' voto':' votos')));content.append(row);});content.append(item('p',poll.total+' votos en total · Los porcentajes están redondeados.','poll-total'));if(voted!==null)content.append(item('p','Tu voto quedó registrado en este navegador.'));if(poll.abierta&&voted===null){const back=item('button','QUIERO VOTAR');back.type='button';back.onclick=()=>{showResults=false;draw();};content.append(back);}}
else{const form=document.createElement('form'),fieldset=document.createElement('fieldset');fieldset.append(item('legend','Elegí una opción'));poll.opciones.forEach((option,i)=>{const label=item('label','','poll-option'),input=document.createElement('input');input.type='radio';input.name='pollOption';input.value=i;input.required=true;label.append(input,item('span',option));fieldset.append(label);});const submit=item('button','VOTAR');submit.type='submit';const results=item('button','VER RESULTADOS','poll-secondary');results.type='button';results.onclick=()=>{showResults=true;draw();};form.append(fieldset,submit,results);form.onsubmit=async e=>{e.preventDefault();if(busy)return;const value=new FormData(form).get('pollOption');if(value===null)return;let visitor;try{visitor=device();}catch{status.textContent='Para votar, permití el almacenamiento de este sitio en tu navegador.';return;}busy=true;submit.disabled=true;status.textContent='Registrando tu voto…';try{const {data,error}=await sb.rpc('zeta_votar',{p_encuesta:poll.id,p_visitante:visitor,p_opcion:Number(value)});if(error)throw error;try{localStorage.setItem('zeta24_vote_'+poll.id,String(data.opcion));}catch{}showResults=true;await loadPoll();status.textContent='¡Gracias por participar!';}catch(error){status.textContent='No se registró un nuevo voto. '+(error.message||'Intentá nuevamente.');}finally{busy=false;submit.disabled=false;}};content.append(form);}}
async function loadPoll(){const id=++refreshId;try{const {data,error}=await sb.rpc('zeta_encuesta_actual');if(error)throw error;if(id!==refreshId)return;const previous=poll?.id;poll=data;if(previous!==poll?.id)showResults=false;draw();status.textContent=poll?(poll.abierta?'Encuesta abierta.':'Votación finalizada. Podés consultar los resultados.'):'Todavía no hay una encuesta publicada.';}catch{if(id!==refreshId)return;status.textContent='La encuesta no está disponible por el momento.';if(!poll)content.replaceChildren();const retry=item('button','VOLVER A INTENTAR','poll-secondary');retry.type='button';retry.onclick=()=>{retry.remove();loadPoll();};if(!content.querySelector('.poll-secondary'))content.append(retry);}}
const editor=el('pollEditorForm'),editorStatus=el('pollEditorStatus');editor.onsubmit=async e=>{e.preventDefault();const fd=new FormData(editor),question=fd.get('question').trim(),options=fd.get('options').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(question.length<5||question.length>200||options.length<2||options.length>5||options.some(s=>s.length>100)||new Set(options.map(s=>s.toLocaleLowerCase())).size!==options.length){editorStatus.textContent='Escribí una pregunta de 5 a 200 caracteres y de 2 a 5 opciones distintas, de hasta 100 caracteres.';return;}const button=editor.querySelector('button[type="submit"]');button.disabled=true;editorStatus.textContent='Publicando…';try{const {error}=await sb.rpc('zeta_publicar_encuesta',{p_pregunta:question,p_opciones:options,p_horas:Number(fd.get('hours'))});if(error)throw error;editor.reset();await loadPoll();editorStatus.textContent='Encuesta publicada. La anterior quedó cerrada.';}catch(error){editorStatus.textContent='No se pudo publicar: '+error.message;}finally{button.disabled=false;}};
el('closePollBtn').onclick=async e=>{if(!poll?.abierta){editorStatus.textContent='No hay una encuesta abierta para cerrar.';return;}e.target.disabled=true;try{const {error}=await sb.rpc('zeta_cerrar_encuesta',{p_encuesta:poll.id});if(error)throw error;await loadPoll();editorStatus.textContent='Encuesta cerrada. Los resultados siguen disponibles.';}catch(error){editorStatus.textContent='No se pudo cerrar: '+error.message;}finally{e.target.disabled=false;}};
loadPoll();setInterval(()=>{if(!document.hidden&&!busy)loadPoll();},60000);
})();
