(()=>{'use strict';
const get=id=>document.getElementById(id),status=get('weatherStatus');
const places={sanmartin:{name:'San Martín',admin1:'Mendoza',country:'Argentina',latitude:-33.081,longitude:-68.469},mendoza:{name:'Mendoza',country:'Argentina',latitude:-32.89,longitude:-68.83},buenosaires:{name:'Buenos Aires',country:'Argentina',latitude:-34.604,longitude:-58.382}};
let request=0,searchRequest=0,started=false;
const num=(v,suffix='')=>Number.isFinite(v)?Math.round(v)+suffix:'—';
const label=p=>[p.name,p.admin1,p.country].filter(Boolean).join(' · ');
function condition(c){if(c===0)return ['☀','Despejado'];if(c<=3)return ['☁','Parcialmente nublado'];if(c<=48)return ['≋','Niebla'];if(c<=67)return ['☂','Lluvia o llovizna'];if(c<=77)return ['❄','Nieve'];if(c<=82)return ['☂','Chaparrones'];if(c<=86)return ['❄','Nevadas'];if(c>=95)return ['ϟ','Tormentas'];return ['☁','Sin descripción'];}
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
async function json(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.error)throw Error(d.reason);return d;}finally{clearTimeout(timer);}}
async function forecast(p){started=true;const id=++request;get('weatherCurrent').replaceChildren();get('weatherDays').replaceChildren();status.textContent='Consultando '+label(p)+'…';try{const q=new URLSearchParams({latitude:p.latitude,longitude:p.longitude,current:'temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max',timezone:'auto',forecast_days:'7'});const d=await json('https://api.open-meteo.com/v1/forecast?'+q);if(id!==request)return;if(!d.current||!d.daily?.time?.length)throw Error('Sin datos');const c=d.current,w=condition(c.weather_code),box=node('div','','current-weather');box.append(node('div',w[0],'weather-icon'));const content=node('div','');content.append(node('h4',label(p)),node('strong',num(c.temperature_2m,' °C'),'current-temp'),node('p',w[1]+' · Sensación '+num(c.apparent_temperature,' °C')),node('p','Viento '+num(c.wind_speed_10m,' km/h')+' · Humedad '+num(c.relative_humidity_2m,'%')));box.append(content);get('weatherCurrent').append(box);d.daily.time.forEach((day,i)=>{const f=d.daily,card=node('article','','day-weather'),w=condition(f.weather_code[i]);card.append(node('h4',new Date(day+'T12:00:00').toLocaleDateString('es-AR',{weekday:'short',day:'numeric',month:'short'})),node('div',w[0],'day-icon'),node('p',w[1]),node('strong',num(f.temperature_2m_max[i],'°')+' / '+num(f.temperature_2m_min[i],'°')),node('small','Prob. lluvia '+num(f.precipitation_probability_max[i],'%')),node('small','Agua '+(Number.isFinite(f.precipitation_sum[i])?f.precipitation_sum[i]+' mm':'—')),node('small','Viento máx. '+num(f.wind_speed_10m_max[i],' km/h')));get('weatherDays').append(card);});status.textContent='Datos del modelo: '+c.time.replace('T',' · ')+' ('+d.timezone+'). Consultado a las '+new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})+'.';}catch(e){if(id!==request)return;status.textContent='No se pudo cargar el pronóstico. Podés volver a intentarlo eligiendo una ciudad. Meteored y los accesos oficiales siguen disponibles.';}}
get('cityForm').addEventListener('submit',async e=>{e.preventDefault();const name=get('citySearch').value.trim();if(name.length<2)return;const id=++searchRequest,res=get('cityResults');res.replaceChildren(node('p','Buscando localidades…'));try{const d=await json('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name,count:8,language:'es',format:'json'}));if(id!==searchRequest)return;res.replaceChildren();if(!d.results?.length){res.append(node('p','No encontramos esa localidad. Probá con el nombre de la ciudad sin la provincia.'));return;}res.append(node('p','Elegí la localidad:'));for(const p of d.results){const b=node('button',label(p));b.type='button';b.onclick=()=>{res.replaceChildren();forecast(p);};res.append(b);}}catch{if(id===searchRequest)res.replaceChildren(node('p','No pudimos completar la búsqueda. Intentá nuevamente.'));}});
document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{searchRequest++;get('cityResults').replaceChildren();forecast(places[b.dataset.city]);});
if('IntersectionObserver' in window){const o=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){if(!started)forecast(places.sanmartin);o.disconnect();}},{rootMargin:'200px'});o.observe(get('clima'));}else forecast(places.sanmartin);
})();
